// CSS custom properties generator.
// Emits a :root block with all tokens flattened into kebab-case variables.

export function toCss(tokens) {
  const lines = [];
  lines.push(`/* Generated by DesignDNA — brand: ${tokens.brand} */`);
  lines.push(':root {');

  // Colors
  for (const [name, value] of Object.entries(tokens.colors || {})) {
    lines.push(`  --color-${name}: ${value};`);
  }

  // Typography
  const typo = tokens.typography || {};
  (typo.families || []).forEach((fam, i) => {
    lines.push(`  --font-family-${i + 1}: "${fam}", system-ui, sans-serif;`);
  });
  for (const [k, v] of Object.entries(typo.sizes || {})) {
    lines.push(`  --font-size-${k}: ${v};`);
  }
  (typo.weights || []).forEach((w, i) => {
    lines.push(`  --font-weight-${i + 1}: ${w};`);
  });

  // Spacing
  for (const [k, v] of Object.entries(tokens.spacing || {})) {
    lines.push(`  --${k}: ${v};`);
  }

  // Radius
  for (const [k, v] of Object.entries(tokens.radius || {})) {
    lines.push(`  --${k}: ${v};`);
  }

  // Shadows
  for (const [k, v] of Object.entries(tokens.shadows || {})) {
    lines.push(`  --${k}: ${v};`);
  }

  lines.push('}');
  lines.push('');
  return lines.join('\n');
}
