// Tailwind CSS preset generator.
// Outputs a `tailwind.config.js` fragment that extends the theme with
// the brand's colors, fonts, radii, shadows, and spacing.

export function toTailwind(tokens) {
  const cfg = {
    theme: {
      extend: {
        colors: tokens.colors || {},
        fontFamily: {},
        fontSize: tokens.typography?.sizes || {},
        borderRadius: tokens.radius || {},
        boxShadow: tokens.shadows || {},
        spacing: tokens.spacing || {},
      },
    },
  };

  // font families — Tailwind expects an array of strings
  (tokens.typography?.families || []).forEach((fam, i) => {
    const key = i === 0 ? 'sans' : `display-${i + 1}`;
    cfg.theme.extend.fontFamily[key] = [fam, 'system-ui', 'sans-serif'];
  });

  const js = stringify(cfg);

  return `/** Generated by DesignDNA — brand: ${tokens.brand} */\n` +
         `/** @type {import('tailwindcss').Config} */\n` +
         `module.exports = ${js};\n`;
}

/**
 * Stringify an object as JavaScript (not JSON) — unquoted keys where valid.
 * Keeps the output readable and idiomatic for tailwind.config.js.
 */
function stringify(value, indent = 0) {
  const pad = '  '.repeat(indent);
  const padNext = '  '.repeat(indent + 1);

  if (value === null) return 'null';
  if (typeof value === 'string') return JSON.stringify(value);
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    return '[\n' + value.map((v) => padNext + stringify(v, indent + 1)).join(',\n') + '\n' + pad + ']';
  }
  if (typeof value === 'object') {
    const keys = Object.keys(value);
    if (keys.length === 0) return '{}';
    return '{\n' + keys.map((k) => {
      const safeKey = /^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k);
      return padNext + safeKey + ': ' + stringify(value[k], indent + 1);
    }).join(',\n') + '\n' + pad + '}';
  }
  return 'undefined';
}
