// TypeScript token generator.
// Emits a `const tokens = {...} as const` object so consumers get literal types.

export function toTypeScript(tokens) {
  const body = JSON.stringify(tokens, null, 2);
  return `/** Generated by DesignDNA — brand: ${tokens.brand} */\n` +
         `export const tokens = ${body} as const;\n` +
         `\nexport type DesignTokens = typeof tokens;\n`;
}
