/** Generated by DesignDNA — brand: nvidia */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "nvidia-green": "#76b900",
        "true-black": "#000000",
        "pure-white": "#ffffff",
        "nvidia-green-light": "#bff230",
        "orange-400": "#df6500",
        "yellow-300": "#ef9100",
        "yellow-050": "#feeeb2",
        "red-500": "#e52020",
        "red-800": "#650b0b",
        "green-500": "#3f8500",
        "blue-700": "#0046a4",
        "purple-800": "#4d1368",
        "purple-100": "#f9d4ff",
        "fuchsia-700": "#8c1c55",
        "gray-300": "#a7a7a7",
        "gray-400": "#898989",
        "gray-500": "#757575",
        "gray-border": "#5e5e5e",
        "near-black": "#1a1a1a",
        "link-hover": "#3860be",
        "button-hover": "#1eaedb",
        "button-active": "#007fff",
        "card-shadow": "rgba(0, 0, 0, 0.3)"
      },
      fontFamily: {
        sans: [
          "NVIDIA-EMEA",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Arial",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Icon Font",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Font Awesome 6 Pro",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "36px",
        "section-heading": "24px",
        "sub-heading": "22px",
        "card-title": "20px",
        body: "18px",
        large: "18px",
        button: "16px",
        link: "14px",
        "link-uppercase": "14px",
        caption: "14px",
        label: "10px",
        micro: "11px"
      },
      borderRadius: {
        "radius-1": "2px"
      },
      boxShadow: {
        "card-shadow": "rgba(0, 0, 0, 0.3"
      },
      spacing: {
        "space-1": "2px",
        "space-2": "3px",
        "space-3": "4px",
        "space-4": "5px",
        "space-5": "6px",
        "space-6": "7px",
        "space-7": "8px",
        "space-8": "9px",
        "space-9": "10px",
        "space-10": "11px"
      }
    }
  }
};
