/** Generated by DesignDNA — brand: sanity */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "sanity-black": "#0b0b0b",
        "pure-black": "#000000",
        "sanity-red": "#f36458",
        "electric-blue": "#0052ef",
        "light-blue": "#55beff",
        "dark-gray": "#212121",
        "medium-dark": "#353535",
        "pure-white": "#ffffff",
        "light-gray": "#ededed",
        silver: "#b9b9b9",
        "medium-gray": "#797979",
        "error-red": "#dd0000",
        "gpc-green": "#37cd84"
      },
      fontFamily: {
        sans: [
          "waldenburgNormal",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "waldenburgNormal Fallback",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "IBM Plex Mono",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "ibmPlexMono Fallback",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "112px",
        "section-heading": "48px",
        large: "38px",
        "heading-medium": "32px",
        small: "24px",
        subheading: "20px",
        body: "18px",
        caption: "13px",
        label: "11px",
        "code-micro": "12px"
      },
      borderRadius: {
        "radius-1": "99999px",
        "radius-2": "5px",
        "radius-3": "6px",
        "radius-4": "12px",
        "radius-5": "3px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "2px",
        "space-2": "4px",
        "space-3": "6px",
        "space-4": "8px",
        "space-5": "12px",
        "space-6": "16px",
        "space-7": "24px",
        "space-8": "32px",
        "space-9": "48px",
        "space-10": "120px"
      }
    }
  }
};
