/** Generated by DesignDNA — brand: sanity */
export const tokens = {
  "brand": "sanity",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "sanity-black": "#0b0b0b",
    "pure-black": "#000000",
    "sanity-red": "#f36458",
    "electric-blue": "#0052ef",
    "light-blue": "#55beff",
    "dark-gray": "#212121",
    "medium-dark": "#353535",
    "pure-white": "#ffffff",
    "light-gray": "#ededed",
    "silver": "#b9b9b9",
    "medium-gray": "#797979",
    "error-red": "#dd0000",
    "gpc-green": "#37cd84"
  },
  "typography": {
    "families": [
      "waldenburgNormal",
      "waldenburgNormal Fallback",
      "IBM Plex Mono",
      "ibmPlexMono Fallback"
    ],
    "sizes": {
      "hero": "112px",
      "section-heading": "48px",
      "large": "38px",
      "heading-medium": "32px",
      "small": "24px",
      "subheading": "20px",
      "body": "18px",
      "caption": "13px",
      "label": "11px",
      "code-micro": "12px"
    },
    "weights": [
      400,
      425,
      500,
      600
    ]
  },
  "spacing": {
    "space-1": "2px",
    "space-2": "4px",
    "space-3": "6px",
    "space-4": "8px",
    "space-5": "12px",
    "space-6": "16px",
    "space-7": "24px",
    "space-8": "32px",
    "space-9": "48px",
    "space-10": "120px"
  },
  "radius": {
    "radius-1": "99999px",
    "radius-2": "5px",
    "radius-3": "6px",
    "radius-4": "12px",
    "radius-5": "3px"
  },
  "shadows": {},
  "dials": {
    "formality": 7,
    "motion": 4,
    "density": 5,
    "warmth": 5,
    "contrast": 7
  }
} as const;

export type DesignTokens = typeof tokens;
