/** Generated by DesignDNA — brand: revolut */
export const tokens = {
  "brand": "revolut",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "revolut-dark": "#191c1f",
    "pure-white": "#ffffff",
    "light-surface": "#f4f4f4",
    "revolut-blue": "#494fdf",
    "action-blue": "#4f55f1",
    "blue-text": "#376cd5",
    "danger-red": "#e23b4a",
    "deep-pink": "#e61e49",
    "warning-orange": "#ec7e00",
    "yellow": "#b09000",
    "teal": "#00a87e",
    "light-green": "#428619",
    "green-text": "#006400",
    "light-blue": "#007bc2",
    "brown": "#936d62",
    "red-text": "#8b0000",
    "mid-slate": "#505a63",
    "cool-gray": "#8d969e",
    "gray-tone": "#c9c9cd"
  },
  "typography": {
    "families": [
      "Aeonik Pro",
      "Inter",
      "Fallback",
      "Arial"
    ],
    "sizes": {
      "display": "136px",
      "hero": "80px",
      "section-heading": "48px",
      "sub-heading": "40px",
      "card-title": "32px",
      "feature-title": "24px",
      "nav-ui": "20px",
      "body": "18px"
    },
    "weights": [
      400,
      500,
      600,
      700
    ]
  },
  "spacing": {
    "space-1": "4px",
    "space-2": "6px",
    "space-3": "8px",
    "space-4": "14px",
    "space-5": "16px",
    "space-6": "20px",
    "space-7": "24px",
    "space-8": "32px",
    "space-9": "40px",
    "space-10": "48px"
  },
  "radius": {
    "radius-1": "9999px",
    "radius-2": "12px"
  },
  "shadows": {},
  "dials": {
    "formality": 7,
    "motion": 6,
    "density": 6,
    "warmth": 4,
    "contrast": 8
  }
} as const;

export type DesignTokens = typeof tokens;
