/** Generated by DesignDNA — brand: figma */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "pure-black": "#000000",
        "pure-white": "#ffffff",
        "glass-black": "rgba(0, 0, 0, 0.08)",
        "glass-white": "rgba(255, 255, 255, 0.16)"
      },
      fontFamily: {
        sans: [
          "figmaSans",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "figmaSans Fallback",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "figmaMono",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "figmaMono Fallback",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "86px",
        "section-heading": "64px",
        "sub-heading": "26px",
        "sub-heading-light": "26px",
        "feature-title": "24px",
        body: "20px",
        label: "18px",
        small: "12px"
      },
      borderRadius: {
        "radius-1": "6px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "2px",
        "space-2": "4px",
        "space-3": "4.5px",
        "space-4": "8px",
        "space-5": "10px",
        "space-6": "12px",
        "space-7": "16px",
        "space-8": "18px",
        "space-9": "24px",
        "space-10": "32px"
      }
    }
  }
};
