/** Generated by DesignDNA — brand: figma */
export const tokens = {
  "brand": "figma",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "pure-black": "#000000",
    "pure-white": "#ffffff",
    "glass-black": "rgba(0, 0, 0, 0.08)",
    "glass-white": "rgba(255, 255, 255, 0.16)"
  },
  "typography": {
    "families": [
      "figmaSans",
      "figmaSans Fallback",
      "figmaMono",
      "figmaMono Fallback"
    ],
    "sizes": {
      "hero": "86px",
      "section-heading": "64px",
      "sub-heading": "26px",
      "sub-heading-light": "26px",
      "feature-title": "24px",
      "body": "20px",
      "label": "18px",
      "small": "12px"
    },
    "weights": [
      320,
      330,
      340,
      400,
      450,
      540,
      700
    ]
  },
  "spacing": {
    "space-1": "2px",
    "space-2": "4px",
    "space-3": "4.5px",
    "space-4": "8px",
    "space-5": "10px",
    "space-6": "12px",
    "space-7": "16px",
    "space-8": "18px",
    "space-9": "24px",
    "space-10": "32px"
  },
  "radius": {
    "radius-1": "6px"
  },
  "shadows": {},
  "dials": {
    "formality": 4,
    "motion": 7,
    "density": 5,
    "warmth": 7,
    "contrast": 7
  }
} as const;

export type DesignTokens = typeof tokens;
