/** Generated by DesignDNA — brand: elevenlabs */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "pure-white": "#ffffff",
        "light-gray": "#f5f5f5",
        "warm-stone": "#f5f2ef",
        black: "#000000",
        "dark-gray": "#4e4e4e",
        "warm-gray": "#777169",
        "near-white": "#f6f6f6",
        "grid-cyan": "#7fffff",
        "ring-blue": "rgb(147 197 253 / 0.5)",
        "border-light": "#e5e5e5",
        "border-subtle": "rgba(0, 0, 0, 0.05)",
        "inset-border": "rgba(0, 0, 0, 0.075)",
        "inset-dark": "rgba(0, 0, 0, 0.1)",
        "outline-ring": "rgba(0, 0, 0, 0.06)",
        "soft-elevation": "rgba(0, 0, 0, 0.04)",
        "card-shadow": "rgba(0, 0, 0, 0.4)",
        "warm-shadow": "rgba(78, 50, 23, 0.04)",
        "edge-shadow": "rgba(0, 0, 0, 0.08)"
      },
      fontFamily: {
        sans: [
          "Waldenburg",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Waldenburg Fallback",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Display Bold",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "WaldenburgFH",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "48px",
        "section-heading": "36px",
        "card-heading": "32px",
        body: "20px",
        "nav-ui": "15px",
        button: "15px",
        caption: "14px",
        small: "13px",
        code: "13px",
        micro: "12px",
        tiny: "10px"
      },
      borderRadius: {
        "radius-1": "9999px",
        "radius-2": "30px",
        "radius-3": "16px"
      },
      boxShadow: {
        "card-shadow": "rgba(0,0,0,0.4",
        "warm-shadow": "rgba(78,50,23,0.04",
        "edge-shadow": "rgba(0,0,0,0.08"
      },
      spacing: {
        "space-1": "3px",
        "space-2": "4px",
        "space-3": "8px",
        "space-4": "9px",
        "space-5": "10px",
        "space-6": "11px",
        "space-7": "12px",
        "space-8": "16px",
        "space-9": "18px",
        "space-10": "20px"
      }
    }
  }
};
