/** Generated by DesignDNA — brand: coinbase */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "coinbase-blue": "#0052ff",
        "pure-white": "#ffffff",
        "near-black": "#0a0b0d",
        "cool-gray-surface": "#eef0f3",
        "hover-blue": "#578bfa",
        "link-blue": "#0667d0",
        "muted-blue": "#5b616e",
        "dark-card": "#282b31",
        "light-surface": "rgba(247, 247, 247, 0.88)"
      },
      fontFamily: {
        sans: [
          "CoinbaseDisplay",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "CoinbaseSans",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Body",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "CoinbaseText",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "80px",
        display: "64px",
        "section-heading": "36px",
        "card-title": "32px",
        "feature-title": "18px",
        body: "16px",
        button: "16px",
        caption: "14px",
        small: "13px"
      },
      borderRadius: {
        "radius-1": "56px",
        "radius-2": "8px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "3px",
        "space-2": "4px",
        "space-3": "5px",
        "space-4": "6px",
        "space-5": "8px",
        "space-6": "10px",
        "space-7": "12px",
        "space-8": "15px",
        "space-9": "16px",
        "space-10": "20px"
      }
    }
  }
};
