/** Generated by DesignDNA — brand: lovable */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        cream: "#f7f4ed",
        charcoal: "#1c1c1c",
        "off-white": "#fcfbf8",
        "muted-gray": "#5f5f5d",
        "light-cream": "#eceae4",
        "ring-blue": "#3b82f6",
        "focus-shadow": "rgba(0, 0, 0, 0.1)",
        "button-inset": "rgba(255, 255, 255, 0.2)"
      },
      fontFamily: {
        sans: [
          "Camera Plain Variable",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "ui-sans-serif",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Weight range",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Feature",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "60px",
        display: "60px",
        "section-heading": "48px",
        "sub-heading": "36px",
        "card-title": "20px",
        body: "18px",
        button: "16px",
        small: "14px",
        link: "16px",
        caption: "14px"
      },
      borderRadius: {
        "radius-1": "6px",
        "radius-2": "9999px",
        "radius-3": "12px"
      },
      boxShadow: {
        "shadow-1": "rgba(255,255,255,0.2) 0px 0.5px 0px 0px inset, rgba(0,0,0,0.2) 0px 0px 0px 0.5px inset, rgba(0,0,0,0.05) 0px 1px 2px 0px"
      },
      spacing: {
        "space-1": "8px",
        "space-2": "10px",
        "space-3": "12px",
        "space-4": "16px",
        "space-5": "24px",
        "space-6": "32px",
        "space-7": "40px",
        "space-8": "56px",
        "space-9": "80px",
        "space-10": "96px"
      }
    }
  }
};
