/** Generated by DesignDNA — brand: resend */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "void-black": "#000000",
        "near-white": "#f0f0f0",
        "pure-white": "#ffffff",
        "orange-4": "#ff5900",
        "orange-10": "#ff801f",
        "orange-11": "#ffa057",
        "green-3": "#22ff99",
        "green-4": "#11ff99",
        "blue-4": "#0075ff",
        "blue-5": "#0081fd",
        "blue-10": "#3b9eff",
        "yellow-9": "#ffc53d",
        "red-5": "#ff2047",
        silver: "#a1a4a5",
        "dark-gray": "#464a4d",
        "mid-gray": "#5c5c5c",
        "medium-gray": "#494949",
        "light-gray": "#f8f8f8",
        "border-gray": "#eaeaea",
        "edge-gray": "#ececec",
        "mist-gray": "#dedfdf",
        "soft-gray": "#e5e6e6",
        "frost-primary": "#fcfdff",
        "white-hover": "rgba(255, 255, 255, 0.28)",
        "frost-border": "rgba(214, 235, 253, 0.19)",
        "frost-border-alt": "rgba(217, 237, 254, 0.145)",
        "ring-shadow": "rgba(176, 199, 217, 0.145)",
        "focus-ring": "rgb(0, 0, 0)",
        "subtle-shadow": "rgba(0, 0, 0, 0.1)"
      },
      fontFamily: {
        sans: [
          "Display Serif",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "domaine",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Display Sans",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "aBCFavorit",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "96px",
        "section-heading": "56px",
        "sub-heading": "20px",
        "sub-heading-compact": "16px",
        "feature-title": "24px",
        body: "18px",
        "nav-link": "14px",
        button: "14px",
        caption: "14px",
        small: "12px",
        "code-tiny": "12px",
        "heading-helvetica": "24px"
      },
      borderRadius: {
        "radius-1": "9999px",
        "radius-2": "4px",
        "radius-3": "16px"
      },
      boxShadow: {
        "ring-shadow": "rgba(176, 199, 217, 0.145",
        "subtle-shadow": "rgba(0, 0, 0, 0.1"
      },
      spacing: {
        "space-1": "2px",
        "space-2": "4px",
        "space-3": "5px",
        "space-4": "6px",
        "space-5": "7px",
        "space-6": "8px",
        "space-7": "10px",
        "space-8": "12px",
        "space-9": "16px",
        "space-10": "20px"
      }
    }
  }
};
