/** Generated by DesignDNA — brand: lamborghini */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "lamborghini-gold": "#ffc000",
        "pure-white": "#ffffff",
        "dark-gold": "#917300",
        "gold-text": "#ffce3e",
        "cyan-pulse": "#29abe2",
        "link-blue": "#3860be",
        "absolute-black": "#000000",
        charcoal: "#202020",
        "dark-iron": "#181818",
        "overlay-black": "rgba(0, 0, 0, 0.7)",
        "near-white": "#f8f8f8",
        mist: "#e6e6e6",
        smoke: "#f5f5f5",
        graphite: "#494949",
        ash: "#7d7d7d",
        steel: "#969696",
        slate: "#666666",
        iron: "#555555",
        shadow: "#313131",
        "teal-action": "#1eaedb"
      },
      fontFamily: {
        sans: [
          "LamboType",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Open Sans",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        display: "120px",
        large: "18px",
        small: "13px",
        caption: "14px",
        hero: "120px",
        "section-title": "54px",
        "sub-section": "40px",
        "feature-heading": "27px",
        "card-title": "24px",
        body: "18px",
        button: "14.4px",
        label: "12px",
        micro: "10px"
      },
      borderRadius: {
        "radius-1": "0px",
        "radius-2": "20px",
        "radius-3": "2px"
      },
      boxShadow: {
        "shadow-1": "rgba(0,0,0,0.7)",
        "shadow-2": "rgba(0,0,0,0.5)",
        "shadow-3": "rgba(0,0,0,0.25)"
      },
      spacing: {
        "space-1": "2px",
        "space-2": "4px",
        "space-3": "5px",
        "space-4": "8px",
        "space-5": "10px",
        "space-6": "12px",
        "space-7": "15px",
        "space-8": "16px",
        "space-9": "20px",
        "space-10": "24px"
      }
    }
  }
};
