/** Generated by DesignDNA — brand: tesla */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "electric-blue": "#3e6ae1",
        "pure-white": "#ffffff",
        "light-ash": "#f4f4f4",
        "carbon-dark": "#171a20",
        "frosted-glass": "rgba(255, 255, 255, 0.75)",
        graphite: "#393c41",
        pewter: "#5c5e62",
        "silver-fog": "#8e8e8e",
        "cloud-gray": "#eeeeee",
        "pale-silver": "#d0d1d2"
      },
      fontFamily: {
        sans: [
          "Universal Sans Display",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Universal Sans Text",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "40px",
        "product-name": "17px",
        "nav-item": "14px",
        body: "14px",
        button: "14px",
        "sub-link": "14px",
        "promo-text": "22px",
        label: "16px"
      },
      borderRadius: {
        "radius-1": "4px"
      },
      boxShadow: {
        "shadow-1": "s entirely in its primary interface. Depth is communicated through three alternative strategies:"
      },
      spacing: {
        "space-1": "4px",
        "space-2": "8px",
        "space-3": "16px"
      }
    }
  }
};
