// `designdna craft` — Two-stage skill model.
//
// Stage 1 (this command): synthesize a PROJECT-DESIGN.md tailored to a user's
//   chosen base brand + optional dial overrides + an optional "blend" brand.
//   The output is a single markdown file dropped into the user's project root.
//
// Stage 2 (downstream): the user's AI coding agent reads PROJECT-DESIGN.md
//   as the single source of truth for every subsequent UI generation.
//
// Examples:
//   npx designdna craft --brand=apple
//   npx designdna craft --brand=linear --motion=7 --density=3
//   npx designdna craft --brand=stripe --blend=vercel --name="Acme Docs"

import { readFile, writeFile, stat } from 'node:fs/promises';
import { resolve, join, isAbsolute } from 'node:path';
import { resolveDesignMdRoot, joinCwd } from '../utils/paths.js';
import { DIALS, dialDistance, nearestBrands } from '../data/dials.js';
import { c, logBanner, logSuccess, logError, logInfo, logStep } from '../utils/log.js';

const DIAL_KEYS = ['formality', 'motion', 'density', 'warmth', 'contrast'];

export async function runCraft({ flags = {} } = {}) {
  const brand = flags.brand;
  if (!brand) {
    logError('Missing --brand=<name>. Example: npx designdna craft --brand=apple');
    logInfo('Run `npx designdna list` to see available brands.');
    process.exit(1);
  }

  const root = resolveDesignMdRoot();
  const brandDir = resolve(root, brand);

  let brandMd, bannedMd;
  try {
    brandMd = await readFile(join(brandDir, 'DESIGN.md'), 'utf8');
  } catch {
    logError(`Brand "${brand}" not found at ${brandDir}`);
    process.exit(1);
  }

  try {
    bannedMd = await readFile(join(brandDir, 'BANNED.md'), 'utf8');
  } catch {
    bannedMd = null; // optional
  }

  // Resolve dials: base brand → overrides from flags → blend with second brand
  const baseDials = { ...(DIALS[brand] || defaultDials()) };
  const dials = applyDialOverrides(baseDials, flags);

  let blendDials = null;
  if (flags.blend) {
    blendDials = DIALS[flags.blend];
    if (!blendDials) {
      logError(`Blend brand "${flags.blend}" not found.`);
      process.exit(1);
    }
    // 50/50 midpoint unless user specified --blend-ratio
    const ratio = parseRatio(flags['blend-ratio'] ?? 0.5);
    for (const k of DIAL_KEYS) {
      dials[k] = Math.round(dials[k] * (1 - ratio) + blendDials[k] * ratio);
    }
  }

  // Sanity clamp
  for (const k of DIAL_KEYS) {
    dials[k] = clamp(dials[k], 1, 10);
  }

  const projectName = flags.name || 'My Project';
  const outPath = flags.out
    ? (isAbsolute(flags.out) ? flags.out : joinCwd(flags.out))
    : joinCwd('PROJECT-DESIGN.md');

  const doc = renderProjectDesign({
    projectName,
    brand,
    blend: flags.blend || null,
    dials,
    brandMd,
    bannedMd,
  });

  await writeFile(outPath, doc);

  logBanner();
  logSuccess(`Crafted ${c.bold('PROJECT-DESIGN.md')} for ${c.bold(projectName)}`);
  console.log(`  ${c.dim('→')} ${outPath}`);
  console.log('');
  console.log(`  ${c.bold('Base brand:')}  ${brand}${flags.blend ? ` ${c.dim('×')} ${flags.blend}` : ''}`);
  console.log(`  ${c.bold('Dials:')}       ${formatDials(dials)}`);
  console.log(`  ${c.bold('Size:')}        ${(doc.length / 1024).toFixed(1)} KB`);
  console.log('');
  const near = nearestBrands(dials, 3).filter((n) => n.brand !== brand).slice(0, 2);
  if (near.length > 0) {
    logStep(`${c.dim('Similar brands in taste space:')} ${near.map((n) => n.brand).join(', ')}`);
  }
  logStep(`${c.dim('Next:')} tell your AI agent — ${c.cyan('"Use PROJECT-DESIGN.md to build the UI"')}`);
  console.log('');
}

/**
 * Render the PROJECT-DESIGN.md content.
 */
function renderProjectDesign({ projectName, brand, blend, dials, brandMd, bannedMd }) {
  const header = `<!--
  PROJECT-DESIGN.md — generated by DesignDNA (https://github.com/tiantangcao1980-web/DesignDNA-Skills)
  This file is the single source of truth for your project's visual design.
  Any AI coding agent should read this file before generating UI.
-->

# ${projectName} — Design System

${blend
  ? `> **Base DNA:** \`${brand}\` blended with \`${blend}\``
  : `> **Base DNA:** \`${brand}\``}
> **Dials:** ${formatDialsMd(dials)}

`;

  const dialsSection = `## Dials (project-specific taste vector)

\`\`\`
DESIGN_VARIANCE   = ${mapVariance(dials)}    # derived from formality+density
FORMALITY         = ${dials.formality}    ${axisLabel('formality', dials.formality)}
MOTION_INTENSITY  = ${dials.motion}    ${axisLabel('motion', dials.motion)}
VISUAL_DENSITY    = ${dials.density}    ${axisLabel('density', dials.density)}
WARMTH            = ${dials.warmth}    ${axisLabel('warmth', dials.warmth)}
CONTRAST          = ${dials.contrast}    ${axisLabel('contrast', dials.contrast)}
\`\`\`

These are the project defaults. Do not reset them to 5,5,5,5,5.
Conditional rules in \`designdna/anti-slop/SKILL.md\` are driven by these values.

`;

  const preflightSection = `## Pre-flight Checklist (mandatory)

Before emitting any UI code, self-audit. This is not optional.

\`\`\`
Typography
- [ ] Font families ONLY from the brand DNA below
- [ ] ≤ 4 font weights used total
- [ ] No Inter unless the brand DNA specifies it

Color
- [ ] No pure #000000 or #FFFFFF
- [ ] No default AI purple (#8B5CF6 family) unless brand specifies
- [ ] Accent color explicitly from brand DNA below

Layout
- [ ] Hero is NOT the centered "headline + subhead + 2 buttons" template
- [ ] No 3-column icon-card feature grid
- [ ] No "Trusted by" fake-logo bar

Copy
- [ ] No "John Doe" / "Acme" / "Nexus" placeholders
- [ ] No fake metrics (99.99%, 10x, 10,000+)
- [ ] No "Effortlessly" / "Seamlessly" / "Revolutionary"

Dials
- [ ] Conditional rules for my dial values are applied
\`\`\`

`;

  let body = `---\n\n## Brand DNA — ${brand}\n\n`;
  body += brandMd.trim() + '\n\n---\n\n';

  if (bannedMd) {
    body += `## BANNED Patterns\n\n`;
    body += bannedMd.trim() + '\n\n---\n\n';
  }

  const footer = `## How to use this file

1. Every UI generation prompt should reference this file: *"Use PROJECT-DESIGN.md to build the ___ page."*
2. If your AI editor supports skills, also install the full DesignDNA skill: \`npx designdna install --ide=claude-code\`.
3. When the design system needs to evolve, edit this file and commit — it's the contract.

## Generated by

[DesignDNA](https://github.com/tiantangcao1980-web/DesignDNA-Skills) — design systems as AI skills.
Based on [awesome-design-md](https://github.com/VoltAgent/awesome-design-md) (design data) and [taste-skill](https://github.com/Leonxlnx/taste-skill) (bias correction).
`;

  return header + dialsSection + preflightSection + body + footer;
}

/* ═══════════════════════════════════════════════════════════════ */

function defaultDials() {
  return { formality: 6, motion: 5, density: 4, warmth: 5, contrast: 7 };
}

function applyDialOverrides(base, flags) {
  const out = { ...base };
  for (const key of DIAL_KEYS) {
    if (flags[key] !== undefined) {
      const n = Number(flags[key]);
      if (Number.isFinite(n)) out[key] = clamp(n, 1, 10);
    }
  }
  return out;
}

function parseRatio(v) {
  if (typeof v === 'string' && v.includes(':')) {
    const [a, b] = v.split(':').map(Number);
    return b / (a + b);
  }
  const n = Number(v);
  return Number.isFinite(n) ? clamp(n, 0, 1) : 0.5;
}

function clamp(n, lo, hi) {
  return Math.max(lo, Math.min(hi, n));
}

function formatDials(d) {
  return DIAL_KEYS.map((k) => `${k}:${d[k]}`).join(' · ');
}

function formatDialsMd(d) {
  return DIAL_KEYS.map((k) => `\`${k}=${d[k]}\``).join(' · ');
}

function mapVariance(d) {
  // higher formality + lower density → more structured = lower variance
  return clamp(10 - Math.round((d.formality + (10 - d.density)) / 2), 1, 10);
}

function axisLabel(axis, v) {
  const labels = {
    formality: ['playful', 'loose', 'neutral', 'polished', 'austere'],
    motion:    ['static', 'subtle', 'present', 'lively', 'heavy'],
    density:   ['breathy', 'airy', 'balanced', 'layered', 'data-dense'],
    warmth:    ['cold', 'clinical', 'neutral', 'warm', 'human'],
    contrast:  ['muted', 'soft', 'balanced', 'bold', 'stark'],
  };
  const bucket = Math.min(Math.floor((v - 1) / 2), 4);
  return `# ${labels[axis]?.[bucket] || ''}`;
}
