/** Generated by DesignDNA — brand: ferrari */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "ferrari-red": "#da291c",
        "pure-white": "#ffffff",
        "dark-red": "#b01e0a",
        "deep-red": "#9d2211",
        "racing-yellow": "#fff200",
        "modena-yellow": "#f6e500",
        "absolute-black": "#000000",
        "dark-surface": "#303030",
        "light-gray-surface": "#d2d2d2",
        "overlay-dark": "hsla(0, 0%, 7%, 0.8)",
        "near-black": "#181818",
        "dark-gray": "#666666",
        "mid-gray": "#8f8f8f",
        "silver-gray": "#969696",
        "warning-red": "#f13a2c",
        "success-green": "#03904a",
        "info-blue": "#4c98b9",
        "link-hover-blue": "#3860be"
      },
      fontFamily: {
        sans: [
          "FerrariSans",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Body-Font",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        caption: "13px",
        "section-title": "26px",
        "card-heading": "24px",
        subheading: "18px",
        "ui-heading": "16px",
        body: "16px",
        button: "16px",
        small: "14.4px",
        "nav-link": "13px",
        label: "12px",
        "cookie-text": "45px"
      },
      borderRadius: {
        "radius-1": "2px",
        "radius-2": "8px"
      },
      boxShadow: {
        "shadow-1": "rgb(153, 153, 153) 1px 1px 1px 0px",
        "shadow-2": "hsla(0, 0%, 7%, 0.8)",
        "shadow-3": "1px solid #CCCCCC",
        "shadow-4": "rgb(153, 153, 153) 1px 1px 1px 0px"
      },
      spacing: {
        "space-1": "2px",
        "space-2": "4px",
        "space-3": "5px",
        "space-4": "6px",
        "space-5": "8px",
        "space-6": "9px",
        "space-7": "10px",
        "space-8": "11.2px",
        "space-9": "12px",
        "space-10": "13px"
      }
    }
  }
};
