/** Generated by DesignDNA — brand: ferrari */
export const tokens = {
  "brand": "ferrari",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "ferrari-red": "#da291c",
    "pure-white": "#ffffff",
    "dark-red": "#b01e0a",
    "deep-red": "#9d2211",
    "racing-yellow": "#fff200",
    "modena-yellow": "#f6e500",
    "absolute-black": "#000000",
    "dark-surface": "#303030",
    "light-gray-surface": "#d2d2d2",
    "overlay-dark": "hsla(0, 0%, 7%, 0.8)",
    "near-black": "#181818",
    "dark-gray": "#666666",
    "mid-gray": "#8f8f8f",
    "silver-gray": "#969696",
    "warning-red": "#f13a2c",
    "success-green": "#03904a",
    "info-blue": "#4c98b9",
    "link-hover-blue": "#3860be"
  },
  "typography": {
    "families": [
      "FerrariSans",
      "Body-Font"
    ],
    "sizes": {
      "caption": "13px",
      "section-title": "26px",
      "card-heading": "24px",
      "subheading": "18px",
      "ui-heading": "16px",
      "body": "16px",
      "button": "16px",
      "small": "14.4px",
      "nav-link": "13px",
      "label": "12px",
      "cookie-text": "45px"
    },
    "weights": [
      400,
      500,
      600,
      700
    ]
  },
  "spacing": {
    "space-1": "2px",
    "space-2": "4px",
    "space-3": "5px",
    "space-4": "6px",
    "space-5": "8px",
    "space-6": "9px",
    "space-7": "10px",
    "space-8": "11.2px",
    "space-9": "12px",
    "space-10": "13px"
  },
  "radius": {
    "radius-1": "2px",
    "radius-2": "8px"
  },
  "shadows": {
    "shadow-1": "rgb(153, 153, 153) 1px 1px 1px 0px",
    "shadow-2": "hsla(0, 0%, 7%, 0.8)",
    "shadow-3": "1px solid #CCCCCC",
    "shadow-4": "rgb(153, 153, 153) 1px 1px 1px 0px"
  },
  "dials": {
    "formality": 9,
    "motion": 4,
    "density": 2,
    "warmth": 5,
    "contrast": 10
  }
} as const;

export type DesignTokens = typeof tokens;
