/** Generated by DesignDNA — brand: ollama */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "pure-black": "#000000",
        "near-black": "#262626",
        "darkest-surface": "#090909",
        "pure-white": "#ffffff",
        snow: "#fafafa",
        "light-gray": "#e5e5e5",
        stone: "#737373",
        "mid-gray": "#525252",
        silver: "#a3a3a3",
        "button-text-dark": "#404040",
        "ring-blue": "#3b82f6",
        "border-light": "#d4d4d4"
      },
      fontFamily: {
        sans: [
          "SF Pro Rounded",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "ui-sans-serif",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Apple Color Emoji",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "SFMono-Regular",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "48px",
        "section-heading": "36px",
        "sub-heading": "30px",
        "card-title": "24px",
        body: "18px",
        caption: "14px",
        small: "12px"
      },
      borderRadius: {},
      boxShadow: {
        "shadow-1": "1px solid #e5e5e5"
      },
      spacing: {
        "space-1": "4px",
        "space-2": "6px",
        "space-3": "8px",
        "space-4": "9px",
        "space-5": "10px",
        "space-6": "12px",
        "space-7": "14px",
        "space-8": "16px",
        "space-9": "20px",
        "space-10": "24px"
      }
    }
  }
};
