/** Generated by DesignDNA — brand: ollama */
export const tokens = {
  "brand": "ollama",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "pure-black": "#000000",
    "near-black": "#262626",
    "darkest-surface": "#090909",
    "pure-white": "#ffffff",
    "snow": "#fafafa",
    "light-gray": "#e5e5e5",
    "stone": "#737373",
    "mid-gray": "#525252",
    "silver": "#a3a3a3",
    "button-text-dark": "#404040",
    "ring-blue": "#3b82f6",
    "border-light": "#d4d4d4"
  },
  "typography": {
    "families": [
      "SF Pro Rounded",
      "ui-sans-serif",
      "Apple Color Emoji",
      "SFMono-Regular"
    ],
    "sizes": {
      "hero": "48px",
      "section-heading": "36px",
      "sub-heading": "30px",
      "card-title": "24px",
      "body": "18px",
      "caption": "14px",
      "small": "12px"
    },
    "weights": [
      400,
      500,
      700
    ]
  },
  "spacing": {
    "space-1": "4px",
    "space-2": "6px",
    "space-3": "8px",
    "space-4": "9px",
    "space-5": "10px",
    "space-6": "12px",
    "space-7": "14px",
    "space-8": "16px",
    "space-9": "20px",
    "space-10": "24px"
  },
  "radius": {},
  "shadows": {
    "shadow-1": "1px solid #e5e5e5"
  },
  "dials": {
    "formality": 8,
    "motion": 2,
    "density": 6,
    "warmth": 3,
    "contrast": 8
  }
} as const;

export type DesignTokens = typeof tokens;
