/** Generated by DesignDNA — brand: bmw */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "pure-white": "#ffffff",
        "bmw-blue": "#1c69d4",
        "bmw-focus-blue": "#0653b6",
        "near-black": "#262626",
        "meta-gray": "#757575",
        silver: "#bbbbbb"
      },
      fontFamily: {
        sans: [
          "Display Light",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "BMWTypeNextLatin Light",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Helvetica",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "BMWTypeNextLatin",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "60px",
        "section-heading": "32px",
        "nav-emphasis": "18px",
        body: "16px",
        button: "16px"
      },
      borderRadius: {},
      boxShadow: {},
      spacing: {
        "space-1": "5px",
        "space-2": "8px",
        "space-3": "10px",
        "space-4": "12px",
        "space-5": "15px",
        "space-6": "16px",
        "space-7": "20px",
        "space-8": "24px",
        "space-9": "30px",
        "space-10": "32px"
      }
    }
  }
};
