/** Generated by DesignDNA — brand: linear.app */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "marketing-black": "#010102",
        "panel-dark": "#0f1011",
        "level-3-surface": "#191a1b",
        "secondary-surface": "#28282c",
        "primary-text": "#f7f8f8",
        "secondary-text": "#d0d6e0",
        "tertiary-text": "#8a8f98",
        "quaternary-text": "#62666d",
        "brand-indigo": "#5e6ad2",
        "accent-violet": "#7170ff",
        "accent-hover": "#828fff",
        "security-lavender": "#7a7fad",
        green: "#27a644",
        emerald: "#10b981",
        "border-primary": "#23252a",
        "border-secondary": "#34343a",
        "border-tertiary": "#3e3e44",
        "border-subtle": "rgba(255, 255, 255, 0.05)",
        "border-standard": "rgba(255, 255, 255, 0.08)",
        "line-tint": "#141516",
        "line-tertiary": "#18191a",
        "light-surface": "#f3f4f5",
        "light-border-alt": "#e6e6e6",
        "pure-white": "#ffffff",
        "overlay-primary": "rgba(0, 0, 0, 0.85)"
      },
      fontFamily: {
        sans: [
          "Inter Variable",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "SF Pro Display",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Berkeley Mono",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "SF Mono",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        display: "72px",
        h1: "32px",
        h2: "24px",
        h3: "20px",
        body: "18px",
        small: "15px",
        caption: "14px",
        label: "12px",
        micro: "11px",
        tiny: "10px",
        large: "16px",
        "link-medium": "15px"
      },
      borderRadius: {
        "radius-1": "6px",
        "radius-2": "9999px",
        "radius-3": "2px",
        "radius-4": "8px",
        "radius-5": "5px"
      },
      boxShadow: {
        "shadow-1": "rgba(0,0,0,0.03) 0px 1.2px 0px",
        "shadow-2": "rgba(255,255,255,0.05)",
        "shadow-3": "1px solid rgba(255,255,255,0.08)",
        "shadow-4": "rgba(0,0,0,0.2) 0px 0px 12px 0px inset",
        "shadow-5": "rgba(0,0,0,0.2) 0px 0px 0px 1px",
        "shadow-6": "rgba(0,0,0,0.4) 0px 2px 4px"
      },
      spacing: {
        "space-1": "4px",
        "space-2": "7px",
        "space-3": "8px",
        "space-4": "11px",
        "space-5": "12px",
        "space-6": "16px",
        "space-7": "19px",
        "space-8": "20px",
        "space-9": "22px",
        "space-10": "24px"
      }
    }
  }
};
