/** Generated by DesignDNA — brand: minimax */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "brand-blue": "#1456f0",
        "sky-blue": "#3daeff",
        "brand-pink": "#ea5ec1",
        "primary-200": "#bfdbfe",
        "primary-light": "#60a5fa",
        "primary-500": "#3b82f6",
        "primary-600": "#2563eb",
        "primary-700": "#1d4ed8",
        "brand-deep": "#17437d",
        "near-black": "#222222",
        dark: "#18181b",
        charcoal: "#181e25",
        "dark-gray": "#45515e",
        "mid-gray": "#8e8e93",
        "light-gray": "#5f5f5f",
        "pure-white": "#ffffff",
        "glass-white": "hsla(0, 0%, 100%, 0.4)",
        "border-light": "#f2f3f5",
        "border-gray": "#e5e7eb",
        "success-background": "#e8ffea",
        standard: "rgba(0, 0, 0, 0.08)",
        "brand-purple": "rgba(44, 30, 116, 0.16)",
        "brand-purple-offset": "rgba(44, 30, 116, 0.11)",
        "card-elevation": "rgba(36, 36, 36, 0.08)"
      },
      fontFamily: {
        sans: [
          "Primary UI",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "DM Sans",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Helvetica Neue",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Outfit",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "80px",
        "section-heading": "31px",
        "section-heading-alt": "32px",
        "card-title": "28px",
        "sub-heading": "24px",
        label: "18px",
        body: "20px",
        navlink: "14px",
        small: "13px",
        caption: "13px",
        micro: "10px"
      },
      borderRadius: {
        "radius-1": "8px",
        "radius-2": "9999px",
        "radius-3": "20px",
        "radius-4": "13px"
      },
      boxShadow: {
        "shadow-1": "rgba(0, 0, 0, 0.08) 0px 4px 6px",
        "shadow-2": "rgba(0, 0, 0, 0.08) 0px 0px 22.576px",
        "shadow-3": "rgba(44, 30, 116, 0.16) 0px 0px 15px",
        "shadow-4": "rgba(44, 30, 116, 0.11) 6.5px 2px 17.5px",
        "shadow-5": "rgba(36, 36, 36, 0.08) 0px 12px 16px -4px"
      },
      spacing: {
        "space-1": "2px",
        "space-2": "4px",
        "space-3": "6px",
        "space-4": "8px",
        "space-5": "10px",
        "space-6": "11px",
        "space-7": "14px",
        "space-8": "16px",
        "space-9": "24px",
        "space-10": "32px"
      }
    }
  }
};
