/** Generated by DesignDNA — brand: hashicorp */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        black: "#000000",
        "dark-charcoal": "#15181e",
        "near-black": "#0d0e12",
        "light-gray": "#f1f2f3",
        "mid-gray": "#d5d7db",
        "cool-gray": "#b2b6bd",
        "dark-gray": "#656a76",
        charcoal: "#3b3d45",
        "near-white": "#efeff1",
        "terraform-purple": "#7b42bc",
        "vault-yellow": "#ffcf25",
        "waypoint-teal": "#14c6cb",
        "waypoint-teal-hover": "#12b6bb",
        "vagrant-blue": "#1868f2",
        "purple-accent": "#911ced",
        "visited-purple": "#a737ff",
        "action-blue": "#1060ff",
        "link-blue": "#2264d6",
        "bright-blue": "#2b89ff",
        amber: "#bb5a00",
        "amber-light": "#fbeabf",
        "vault-faint-yellow": "#fff9cf",
        orange: "#a9722e",
        red: "#731e25",
        navy: "#101a59",
        "micro-shadow": "rgba(97, 104, 117, 0.05)"
      },
      fontFamily: {
        sans: [
          "Primary Brand",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "System UI",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "BlinkMacSystemFont",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "HashiCorp Sans",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "82px",
        "section-heading": "52px",
        "feature-heading": "42px",
        "sub-heading": "34px",
        "card-title": "26px",
        small: "19px",
        body: "17px",
        "nav-link": "15px",
        caption: "13px",
        label: "13px"
      },
      borderRadius: {
        "radius-1": "5px",
        "radius-2": "4px",
        "radius-3": "3px",
        "radius-4": "8px"
      },
      boxShadow: {
        "micro-shadow": "rgba(97, 104, 117, 0.05"
      },
      spacing: {
        "space-1": "2px",
        "space-2": "3px",
        "space-3": "4px",
        "space-4": "6px",
        "space-5": "7px",
        "space-6": "8px",
        "space-7": "9px",
        "space-8": "11px",
        "space-9": "12px",
        "space-10": "16px"
      }
    }
  }
};
