/** Generated by DesignDNA — brand: miro */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "near-black": "#1c1c1e",
        white: "#ffffff",
        "blue-450": "#5b76fe",
        "actionable-pressed": "#2a41b6",
        coral: "#ffc6c6",
        rose: "#ffd8f4",
        teal: "#c3faf5",
        orange: "#ffe6cd",
        yellow: "#746019",
        moss: "#187574",
        pink: "#fde0f0",
        red: "#fbd4d4",
        "dark-red": "#e3c5c5",
        success: "#00b473",
        slate: "#555a6a",
        "input-placeholder": "#a5a8b5",
        border: "#c7cad5",
        ring: "rgb(224, 226, 232)"
      },
      fontFamily: {
        sans: [
          "Roobert PRO Medium",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "blwf",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Display Variants",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Roobert PRO SemiBold",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "56px",
        "section-heading": "48px",
        "card-title": "24px",
        "sub-heading": "22px",
        feature: "18px",
        body: "18px",
        button: "17.5px",
        caption: "14px",
        small: "12px",
        "micro-uppercase": "10.5px"
      },
      borderRadius: {},
      boxShadow: {},
      spacing: {
        "space-1": "24px"
      }
    }
  }
};
