/** Generated by DesignDNA — brand: miro */
export const tokens = {
  "brand": "miro",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "near-black": "#1c1c1e",
    "white": "#ffffff",
    "blue-450": "#5b76fe",
    "actionable-pressed": "#2a41b6",
    "coral": "#ffc6c6",
    "rose": "#ffd8f4",
    "teal": "#c3faf5",
    "orange": "#ffe6cd",
    "yellow": "#746019",
    "moss": "#187574",
    "pink": "#fde0f0",
    "red": "#fbd4d4",
    "dark-red": "#e3c5c5",
    "success": "#00b473",
    "slate": "#555a6a",
    "input-placeholder": "#a5a8b5",
    "border": "#c7cad5",
    "ring": "rgb(224, 226, 232)"
  },
  "typography": {
    "families": [
      "Roobert PRO Medium",
      "blwf",
      "Display Variants",
      "Roobert PRO SemiBold"
    ],
    "sizes": {
      "hero": "56px",
      "section-heading": "48px",
      "card-title": "24px",
      "sub-heading": "22px",
      "feature": "18px",
      "body": "18px",
      "button": "17.5px",
      "caption": "14px",
      "small": "12px",
      "micro-uppercase": "10.5px"
    },
    "weights": [
      400,
      600,
      700
    ]
  },
  "spacing": {
    "space-1": "24px"
  },
  "radius": {},
  "shadows": {},
  "dials": {
    "formality": 5,
    "motion": 6,
    "density": 5,
    "warmth": 7,
    "contrast": 6
  }
} as const;

export type DesignTokens = typeof tokens;
