/** Generated by DesignDNA — brand: spotify */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "spotify-green": "#1ed760",
        "near-black": "#121212",
        "dark-surface": "#181818",
        "mid-dark": "#1f1f1f",
        white: "#ffffff",
        silver: "#b3b3b3",
        "near-white": "#cbcbcb",
        light: "#fdfdfd",
        "negative-red": "#f3727f",
        "warning-orange": "#ffa42b",
        "announcement-blue": "#539df5",
        "dark-card": "#252525",
        "mid-card": "#272727",
        "border-gray": "#4d4d4d",
        "light-border": "#7c7c7c",
        "light-surface": "#eeeeee",
        "spotify-green-border": "#1db954",
        heavy: "rgba(0, 0, 0, 0.5)",
        medium: "rgba(0, 0, 0, 0.3)",
        "inset-border": "rgb(18, 18, 18)"
      },
      fontFamily: {
        sans: [
          "Title",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "SpotifyMixUITitle",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "CircularSp-Arab",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "SpotifyMixUI",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        "section-title": "24px",
        "feature-heading": "18px",
        body: "16px",
        button: "14px",
        "nav-link-bold": "14px",
        "nav-link": "14px",
        caption: "14px",
        small: "12px",
        badge: "10.5px",
        micro: "10px"
      },
      borderRadius: {
        "radius-1": "9999px",
        "radius-2": "500px",
        "radius-3": "6px"
      },
      boxShadow: {
        "shadow-1": "rgba(0,0,0,0.5) 0px 8px 24px",
        "shadow-2": "rgba(0,0,0,0.3) 0px 8px 8px",
        "shadow-3": "rgb(18,18,18) 0px 1px 0px, rgb(124,124,124) 0px 0px 0px 1px inset"
      },
      spacing: {
        "space-1": "2px",
        "space-2": "3px",
        "space-3": "4px",
        "space-4": "5px",
        "space-5": "6px",
        "space-6": "8px",
        "space-7": "10px",
        "space-8": "12px",
        "space-9": "14px",
        "space-10": "15px"
      }
    }
  }
};
