/** Generated by DesignDNA — brand: notion */
export const tokens = {
  "brand": "notion",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "notion-black": "rgba(0, 0, 0, 0.95)",
    "pure-white": "#ffffff",
    "notion-blue": "#0075de",
    "deep-navy": "#213183",
    "active-blue": "#005bab",
    "warm-white": "#f6f5f4",
    "warm-dark": "#31302e",
    "warm-gray-500": "#615d59",
    "warm-gray-300": "#a39e98",
    "teal": "#2a9d99",
    "green": "#1aae39",
    "orange": "#dd5b00",
    "pink": "#ff64c8",
    "purple": "#391c57",
    "brown": "#523410",
    "link-light-blue": "#62aef0",
    "focus-blue": "#097fe8",
    "badge-blue-bg": "#f2f9ff",
    "card-shadow": "rgba(0, 0, 0, 0.04)",
    "deep-shadow": "rgba(0, 0, 0, 0.01)",
    "whisper-border": "rgba(0, 0, 0, 0.1)"
  },
  "typography": {
    "families": [
      "NotionInter",
      "Inter",
      "OpenType Features",
      "lnum"
    ],
    "sizes": {
      "body": "16px",
      "hero": "64px",
      "display": "54px",
      "section-heading": "48px",
      "large": "40px",
      "sub-heading": "26px",
      "card-title": "22px",
      "button": "15px",
      "caption": "14px",
      "badge": "12px",
      "label": "12px"
    },
    "weights": [
      400,
      500,
      600,
      700
    ]
  },
  "spacing": {
    "space-1": "2px",
    "space-2": "3px",
    "space-3": "4px",
    "space-4": "5px",
    "space-5": "5.6px",
    "space-6": "6px",
    "space-7": "6.4px",
    "space-8": "7px",
    "space-9": "8px",
    "space-10": "11px"
  },
  "radius": {
    "radius-1": "4px",
    "radius-2": "9999px",
    "radius-3": "12px"
  },
  "shadows": {
    "card-shadow": "rgba(0,0,0,0.04",
    "deep-shadow": "rgba(0,0,0,0.01"
  },
  "dials": {
    "formality": 5,
    "motion": 3,
    "density": 3,
    "warmth": 8,
    "contrast": 4
  }
} as const;

export type DesignTokens = typeof tokens;
