/** Generated by DesignDNA — brand: zapier */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "zapier-black": "#201515",
        "cream-white": "#fffefb",
        "off-white": "#fffdf9",
        "zapier-orange": "#ff4f00",
        "dark-charcoal": "#36342e",
        "warm-gray": "#939084",
        sand: "#c5c0b1",
        "light-sand": "#eceae3",
        "mid-warm": "#b5b2aa",
        "semi-transparent-dark": "rgba(45, 45, 46, 0.5)",
        "inset-underline": "rgb(255, 79, 0)",
        "hover-underline": "rgb(197, 192, 177)"
      },
      fontFamily: {
        sans: [
          "Degular Display",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Inter",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Helvetica",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Editorial",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        display: "80px",
        hero: "80px",
        "section-heading": "48px",
        "editorial-heading": "48px",
        "editorial-sub": "40px",
        "sub-heading-lg": "36px",
        "sub-heading": "32px",
        "sub-heading-md": "28px",
        "card-title": "24px",
        body: "20px",
        button: "16px",
        caption: "14px",
        micro: "12px",
        "micro-sm": "13px"
      },
      borderRadius: {
        "radius-1": "4px",
        "radius-2": "8px",
        "radius-3": "20px",
        "radius-4": "5px"
      },
      boxShadow: {
        "shadow-1": "rgb(255, 79, 0) 0px -4px 0px 0px inset",
        "shadow-2": "rgb(197, 192, 177) 0px -4px 0px 0px inset"
      },
      spacing: {
        "space-1": "4px",
        "space-2": "6px",
        "space-3": "8px",
        "space-4": "10px",
        "space-5": "12px",
        "space-6": "16px",
        "space-7": "20px",
        "space-8": "24px",
        "space-9": "32px",
        "space-10": "40px"
      }
    }
  }
};
