/** Generated by DesignDNA — brand: zapier */
export const tokens = {
  "brand": "zapier",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "zapier-black": "#201515",
    "cream-white": "#fffefb",
    "off-white": "#fffdf9",
    "zapier-orange": "#ff4f00",
    "dark-charcoal": "#36342e",
    "warm-gray": "#939084",
    "sand": "#c5c0b1",
    "light-sand": "#eceae3",
    "mid-warm": "#b5b2aa",
    "semi-transparent-dark": "rgba(45, 45, 46, 0.5)",
    "inset-underline": "rgb(255, 79, 0)",
    "hover-underline": "rgb(197, 192, 177)"
  },
  "typography": {
    "families": [
      "Degular Display",
      "Inter",
      "Helvetica",
      "Editorial"
    ],
    "sizes": {
      "display": "80px",
      "hero": "80px",
      "section-heading": "48px",
      "editorial-heading": "48px",
      "editorial-sub": "40px",
      "sub-heading-lg": "36px",
      "sub-heading": "32px",
      "sub-heading-md": "28px",
      "card-title": "24px",
      "body": "20px",
      "button": "16px",
      "caption": "14px",
      "micro": "12px",
      "micro-sm": "13px"
    },
    "weights": [
      250,
      300,
      400,
      500,
      600
    ]
  },
  "spacing": {
    "space-1": "4px",
    "space-2": "6px",
    "space-3": "8px",
    "space-4": "10px",
    "space-5": "12px",
    "space-6": "16px",
    "space-7": "20px",
    "space-8": "24px",
    "space-9": "32px",
    "space-10": "40px"
  },
  "radius": {
    "radius-1": "4px",
    "radius-2": "8px",
    "radius-3": "20px",
    "radius-4": "5px"
  },
  "shadows": {
    "shadow-1": "rgb(255, 79, 0) 0px -4px 0px 0px inset",
    "shadow-2": "rgb(197, 192, 177) 0px -4px 0px 0px inset"
  },
  "dials": {
    "formality": 4,
    "motion": 5,
    "density": 5,
    "warmth": 8,
    "contrast": 6
  }
} as const;

export type DesignTokens = typeof tokens;
