/** Generated by DesignDNA — brand: opencode.ai */
export const tokens = {
  "brand": "opencode.ai",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "opencode-dark": "#201d1d",
    "opencode-light": "#fdfcfc",
    "mid-gray": "#9a9898",
    "dark-surface": "#302c2c",
    "border-gray": "#646262",
    "light-surface": "#f1eeee",
    "accent-blue": "#007aff",
    "accent-blue-hover": "#0056b3",
    "accent-blue-active": "#004085",
    "danger-red": "#ff3b30",
    "danger-hover": "#d70015",
    "danger-active": "#a50011",
    "success-green": "#30d158",
    "warning-orange": "#ff9f0a",
    "warning-hover": "#cc7f08",
    "warning-active": "#995f06",
    "text-muted": "#6e6e73",
    "text-secondary": "#424245",
    "border-warm": "rgba(15, 0, 0, 0.12)"
  },
  "typography": {
    "families": [
      "Universal",
      "Berkeley Mono",
      "IBM Plex Mono"
    ],
    "sizes": {
      "body": "16px",
      "caption": "14px",
      "h1": "38px",
      "h2": "16px"
    },
    "weights": [
      400,
      500,
      700
    ]
  },
  "spacing": {
    "space-1": "2px",
    "space-2": "4px",
    "space-3": "8px",
    "space-4": "12px",
    "space-5": "16px",
    "space-6": "20px",
    "space-7": "24px",
    "space-8": "32px",
    "space-9": "40px",
    "space-10": "48px"
  },
  "radius": {
    "radius-1": "4px",
    "radius-2": "6px"
  },
  "shadows": {
    "shadow-1": "1px solid rgba(15, 0, 0, 0.12)",
    "shadow-2": "2px solid #9a9898",
    "shadow-3": "1px solid #646262",
    "shadow-4": "rgba(15, 0, 0, 0.12)"
  },
  "dials": {
    "formality": 6,
    "motion": 5,
    "density": 6,
    "warmth": 3,
    "contrast": 8
  }
} as const;

export type DesignTokens = typeof tokens;
