/** Generated by DesignDNA — brand: intercom */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "off-black": "#111111",
        "pure-white": "#ffffff",
        "warm-cream": "#faf9f6",
        "fin-orange": "#ff5600",
        "report-orange": "#fe4c02",
        "report-blue": "#65b5ff",
        "report-green": "#0bdf50",
        "report-red": "#c41c1c",
        "report-pink": "#ff2067",
        "report-lime": "#b3e01c",
        green: "#00da00",
        "deep-blue": "#0007cb",
        "black-80": "#313130",
        "black-60": "#626260",
        "black-50": "#7b7b78",
        "content-tertiary": "#9c9fa5",
        "oat-border": "#dedbd6",
        "warm-sand": "#d3cec6"
      },
      fontFamily: {
        sans: [
          "Saans",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Saans Fallback",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Serrif",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Serrif Fallback",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "80px",
        "section-heading": "54px",
        "sub-heading": "40px",
        "card-title": "32px",
        "feature-title": "24px",
        body: "20px",
        "nav-ui": "18px",
        button: "16px",
        label: "12px"
      },
      borderRadius: {
        "radius-1": "4px",
        "radius-2": "8px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "8px",
        "space-2": "10px",
        "space-3": "12px",
        "space-4": "14px",
        "space-5": "16px",
        "space-6": "20px",
        "space-7": "24px",
        "space-8": "32px",
        "space-9": "40px",
        "space-10": "48px"
      }
    }
  }
};
