/** Generated by DesignDNA — brand: pinterest */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "pinterest-red": "#e60023",
        "green-700": "#103c25",
        "green-700-hover": "#0b2819",
        "plum-black": "#211922",
        black: "#000000",
        "olive-gray": "#62625b",
        "warm-silver": "#91918c",
        white: "#ffffff",
        "focus-blue": "#435ee5",
        "performance-purple": "#6845ab",
        "recommendation-purple": "#7e238b",
        "link-blue": "#2b48d4",
        "facebook-blue": "#0866ff",
        "pressed-blue": "#617bff",
        "sand-gray": "#e5e5e0",
        "warm-light": "#e0e0d9",
        "warm-wash": "hsla(60, 20%, 98%, 0.5)",
        fog: "#f6f6f3",
        "border-disabled": "#c8c8c1",
        "hover-gray": "#bcbcb3",
        "dark-surface": "#33332e",
        "error-red": "#9e0a0a"
      },
      fontFamily: {
        sans: [
          "Pin Sans",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Segoe UI",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "70px",
        "section-heading": "28px",
        body: "16px",
        caption: "14px",
        button: "12px"
      },
      borderRadius: {
        "radius-1": "16px"
      },
      boxShadow: {},
      spacing: {
        "space-1": "4px",
        "space-2": "6px",
        "space-3": "7px",
        "space-4": "8px",
        "space-5": "10px",
        "space-6": "11px",
        "space-7": "12px",
        "space-8": "16px",
        "space-9": "18px",
        "space-10": "20px"
      }
    }
  }
};
