/** Generated by DesignDNA — brand: webflow */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "near-black": "#080808",
        "webflow-blue": "#146ef5",
        "blue-400": "#3b89ff",
        "blue-300": "#006acc",
        "button-hover-blue": "#0055d4",
        purple: "#7a3dff",
        pink: "#ed52cb",
        green: "#00d722",
        orange: "#ff6b00",
        yellow: "#ffae13",
        red: "#ee1d36",
        "gray-800": "#222222",
        "gray-700": "#363636",
        "gray-300": "#ababab",
        "mid-gray": "#5a5a5a",
        "border-gray": "#d8d8d8",
        "border-hover": "#898989"
      },
      fontFamily: {
        sans: [
          "WF Visual Sans Variable",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Arial",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "80px",
        body: "20px",
        caption: "14px",
        "section-heading": "56px",
        "sub-heading": "32px",
        "feature-title": "24px",
        button: "16px",
        label: "15px",
        "badge-uppercase": "12.8px",
        "micro-uppercase": "10px"
      },
      borderRadius: {},
      boxShadow: {
        "shadow-1": "rgba(0,0,0,0) 0px 84px 24px, rgba(0,0,0,0.01) 0px 54px 22px, rgba(0,0,0,0.04) 0px 30px 18px, rgba(0,0,0,0.08) 0px 13px 13px, rgba(0,0,0,0.09) 0px 3px 7px"
      },
      spacing: {
        "space-1": "2.4px",
        "space-2": "3.2px",
        "space-3": "4px",
        "space-4": "5.6px",
        "space-5": "6px",
        "space-6": "7.2px",
        "space-7": "8px",
        "space-8": "9.6px",
        "space-9": "10px",
        "space-10": "12px"
      }
    }
  }
};
