/** Generated by DesignDNA — brand: clay */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "clay-black": "#000000",
        "pure-white": "#ffffff",
        "warm-cream": "#faf9f7",
        "matcha-300": "#84e7a5",
        "matcha-600": "#078a52",
        "matcha-800": "#02492a",
        "slushie-500": "#3bd3fd",
        "slushie-800": "#0089ad",
        "lemon-400": "#f8cc65",
        "lemon-500": "#fbbd41",
        "lemon-700": "#d08a11",
        "lemon-800": "#9d6a09",
        "ube-300": "#c1b0ff",
        "ube-800": "#43089f",
        "ube-900": "#32037d",
        "pomegranate-400": "#fc7981",
        "blueberry-800": "#01418d",
        "warm-silver": "#9f9b93",
        "warm-charcoal": "#55534e",
        "dark-charcoal": "#333333",
        "oat-border": "#dad4c8",
        "oat-light": "#eee9df",
        "cool-border": "#e6e8ec",
        "dark-border": "#525a69",
        "light-frost": "#eff1f3",
        "badge-blue-bg": "#f0f8ff",
        "badge-blue-text": "#3859f9",
        "focus-ring": "rgb(20, 110, 245)",
        "clay-shadow": "rgba(0, 0, 0, 0.1)",
        "hard-offset": "rgb(0, 0, 0)"
      },
      fontFamily: {
        sans: [
          "Roobert",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "Arial",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "Space Mono",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "OpenType Features",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        hero: "80px",
        display: "60px",
        "section-heading": "44px",
        "card-heading": "32px",
        "feature-title": "20px",
        "sub-heading": "20px",
        body: "20px",
        button: "16px",
        large: "24px",
        small: "12.8px",
        "nav-link": "15px",
        caption: "14px",
        label: "12px",
        badge: "9.6px"
      },
      borderRadius: {
        "radius-1": "4px",
        "radius-2": "12px"
      },
      boxShadow: {
        "clay-shadow": "rgba(0,0,0,0.1"
      },
      spacing: {
        "space-1": "2px",
        "space-2": "4px",
        "space-3": "6.4px",
        "space-4": "8px",
        "space-5": "12px",
        "space-6": "12.8px",
        "space-7": "16px",
        "space-8": "18px",
        "space-9": "20px",
        "space-10": "24px"
      }
    }
  }
};
