/** Generated by DesignDNA — brand: spacex */
export const tokens = {
  "brand": "spacex",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "space-black": "#000000",
    "spectral-white": "#f0f0fa",
    "ghost-surface": "rgba(240, 240, 250, 0.1)",
    "ghost-border": "rgba(240, 240, 250, 0.35)",
    "dark-overlay": "rgba(0, 0, 0, 0.5)"
  },
  "typography": {
    "families": [
      "D-DIN-Bold",
      "D-DIN",
      "Arial"
    ],
    "sizes": {
      "hero": "48px",
      "body": "16px",
      "nav-link-bold": "13px",
      "nav-link": "12px",
      "caption": "13px",
      "micro": "10px"
    },
    "weights": [
      400,
      700
    ]
  },
  "spacing": {
    "space-1": "3px",
    "space-2": "5px",
    "space-3": "8px",
    "space-4": "12px",
    "space-5": "15px",
    "space-6": "18px",
    "space-7": "20px",
    "space-8": "24px",
    "space-9": "30px"
  },
  "radius": {
    "radius-1": "32px"
  },
  "shadows": {
    "shadow-1": "rgba(0, 0, 0, 0.5)",
    "shadow-2": "rgba(240, 240, 250, 0.1)"
  },
  "dials": {
    "formality": 10,
    "motion": 4,
    "density": 2,
    "warmth": 2,
    "contrast": 10
  }
} as const;

export type DesignTokens = typeof tokens;
