/** Generated by DesignDNA — brand: expo */
export const tokens = {
  "brand": "expo",
  "version": "1.0.0",
  "$schema": "https://designdna.dev/schemas/tokens-v1.json",
  "colors": {
    "expo-black": "#000000",
    "near-black": "#1c2024",
    "link-cobalt": "#0d74ce",
    "legal-blue": "#476cff",
    "widget-sky": "#47c2ff",
    "preview-purple": "#8145b5",
    "cloud-gray": "#f0f0f3",
    "pure-white": "#ffffff",
    "widget-dark": "#1a1a1a",
    "banner-dark": "#171717",
    "slate-gray": "#60646c",
    "mid-slate": "#555860",
    "silver": "#b0b4ba",
    "pewter": "#999999",
    "light-silver": "#cccccc",
    "dark-slate": "#363a3f",
    "charcoal": "#333333",
    "warning-amber": "#ab6400",
    "destructive-rose": "#eb8e90",
    "border-lavender": "#e0e1e6",
    "input-border": "#d9d9e0",
    "dark-focus-ring": "#2547d0"
  },
  "typography": {
    "families": [
      "Inter",
      "JetBrains Mono",
      "System Fallback",
      "Segoe UI"
    ],
    "sizes": {
      "hero": "64px",
      "section-heading": "48px",
      "sub-heading": "20px",
      "body": "18px",
      "caption": "14px",
      "small": "12px"
    },
    "weights": [
      400,
      500,
      600,
      700,
      900
    ]
  },
  "spacing": {
    "space-1": "2px",
    "space-2": "4px",
    "space-3": "8px",
    "space-4": "12px",
    "space-5": "16px",
    "space-6": "24px",
    "space-7": "32px",
    "space-8": "40px",
    "space-9": "48px",
    "space-10": "64px"
  },
  "radius": {},
  "shadows": {
    "shadow-1": "rgba(0,0,0,0.08) 0px 3px 6px",
    "shadow-2": "rgba(0,0,0,0.07) 0px 2px 4px",
    "shadow-3": "rgba(0,0,0,0.1) 0px 10px 20px",
    "shadow-4": "rgba(0,0,0,0.05) 0px 3px 6px"
  },
  "dials": {
    "formality": 6,
    "motion": 4,
    "density": 6,
    "warmth": 4,
    "contrast": 7
  }
} as const;

export type DesignTokens = typeof tokens;
