/** Generated by DesignDNA — brand: replicate */
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        "replicate-dark": "#202020",
        "replicate-red": "#ea2804",
        "secondary-red": "#dd4425",
        "status-green": "#2b9a66",
        "github-dark": "#24292e",
        "pure-white": "#ffffff",
        "near-white": "#fcfcfc",
        "medium-gray": "#646464",
        "warm-gray": "#4e4e4e",
        "mid-silver": "#8d8d8d",
        "light-silver": "#bbbbbb",
        "pure-black": "#000000"
      },
      fontFamily: {
        sans: [
          "rb-freigeist-neue",
          "system-ui",
          "sans-serif"
        ],
        "display-2": [
          "ui-sans-serif",
          "system-ui",
          "sans-serif"
        ],
        "display-3": [
          "basier-square",
          "system-ui",
          "sans-serif"
        ],
        "display-4": [
          "Code",
          "system-ui",
          "sans-serif"
        ]
      },
      fontSize: {
        display: "128px",
        hero: "72px",
        "section-heading": "48px",
        "sub-heading": "30px",
        "sub-heading-sans": "38.4px",
        "feature-title": "18px",
        body: "20px",
        caption: "14px",
        small: "12px",
        code: "14px"
      },
      borderRadius: {},
      boxShadow: {
        "shadow-1": "1px solid #202020",
        "shadow-2": "1px solid #ea2804",
        "shadow-3": "1px solid #202020"
      },
      spacing: {
        "space-1": "2px",
        "space-2": "4px",
        "space-3": "6px",
        "space-4": "8px",
        "space-5": "10px",
        "space-6": "12px",
        "space-7": "16px",
        "space-8": "24px",
        "space-9": "32px",
        "space-10": "48px"
      }
    }
  }
};
